name = "akasha-subscriber"
main = "build/worker/shim.mjs"
send_metrics = false
compatibility_date = "2024-10-01"
workers_dev = false
routes = [{ pattern = "www.nahida.im/*", zone_name = "nahida.im" }]
[build]
command = "worker-build --release"
